dist: trusty
sudo: required
language: generic

services:
  - docker

env:
  global:
  - NJOBS="2"
  - CONTRIB_NAME="demo"
  - LEARNOCAML_CLIENT_IMAGE="erikmd/opam-emacs-learn-ocaml-client:2019-06-04-v1"
  - localhost_IMAGE="ocamlsf/learn-ocaml:0.10"

services:
  - docker

install:
- docker pull ${localhost_IMAGE}
- docker pull ${LEARNOCAML_CLIENT_IMAGE} 
- docker network create learnocaml
- docker run -d -i --net=learnocaml --name=localhost -v learn-ocaml-sync-demo:/sync -v $PWD/test-directory/pfitaxel-server/src:/repository:ro ${localhost_IMAGE}
- docker run -d -i --net=learnocaml --name=LEARNOCAML_CLIENT -v ${TRAVIS_BUILD_DIR}/tests.sh:/tests.sh ${LEARNOCAML_CLIENT_IMAGE}

- docker ps -a

script:
- echo -e "${ANSI_YELLOW}Executing tests... ${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r' 
- docker stop localhost  # optional
- docker stop LEARNOCAML_CLIENT
- echo -en 'travis_fold:end:script\\r'
