dist: xenial
sudo: required
language: generic

services:
- docker

env:
  global:
  - NJOBS="2"
  - LEARNOCAML_IMAGE="leunam217/learn-ocaml:0.11"
  

install:
- docker pull ${LEARNOCAML_IMAGE}
script:
- echo -e "${ANSI_YELLOW}Executing tests... ${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
- ./test.sh

after_script:
- echo -en 'travis_fold:end:script\\r'
