dist: trusty
sudo: required
language: generic

services:
  - docker

env:
  global:
  - NJOBS="2"
  - CONTRIB_NAME="demo"
  - LEARNOCAML_CLIENT_IMAGE="erikmd/opam-emacs-learn-ocaml-client:2019-06-04-v1"
  - LEARNOCAML_SERVER_IMAGE="ocamlsf/learn-ocaml:0.10"

services:
  - docker

install:
- docker pull ${LEARNOCAML_SERVER_IMAGE}
- docker pull ${LEARNOCAML_CLIENT_IMAGE}
- docker network create learnocaml 
- docker run -d -i --net=learnocaml --name=LEARNOCAML_SERVER -v $PWD/pfitaxel-server/src:/repository:ro  ${LEARNOCAML_SERVER_IMAGE}
- docker run -d -i --net=learnocaml --name=LEARNOCAML_CLIENT -v ${TRAVIS_BUILD_DIR}/test-directory/tests.sh:/tests.sh -v ${TRAVIS_BUILD_DIR}/learn-ocaml.el:/learn-ocaml.el ${LEARNOCAML_CLIENT_IMAGE}
- docker ps -a

script:
- echo -e "${ANSI_YELLOW}Executing tests... ${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r' 
- docker exec -it LEARNOCAML_CLIENT /tests.sh
- docker stop LEARNOCAML_SERVER  # optional
- docker stop LEARNOCAML_CLIENT
- echo -en 'travis_fold:end:script\\r'
