dist: bionic
language: minimal

services:
  - docker

env:
  global:
  - LEARNOCAML_IMAGE="leunam217/learn-ocaml"
  - LEARNOCAML_VERSION="0.11"

install:
- docker pull "$LEARNOCAML_IMAGE:$LEARNOCAML_VERSION"

script:
- echo -e "${ANSI_YELLOW}Executing tests... ${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
- ./test.sh
- echo -en 'travis_fold:end:script\\r'
