dist: bionic
language: minimal

services:
  - docker

env:
  global:
  - EMACS_IMAGE="pfitaxel/opam-emacs"
  - CLIENT_PATH="/home/coq/.local/bin/learn-ocaml-client"
  - CLIENT_UID="1000"
  - LEARNOCAML_IMAGE="ocamlsf/learn-ocaml"
  - CLIENT_IMAGE="ocamlsf/learn-ocaml-client"
  matrix:
  - LEARNOCAML_VERSION="dev"

install:
- docker pull "$LEARNOCAML_IMAGE:$LEARNOCAML_VERSION"
- docker pull "$CLIENT_IMAGE:$LEARNOCAML_VERSION"
- docker pull "$EMACS_IMAGE"

script:
- echo -e "${ANSI_YELLOW}Executing tests... ${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
- ./test.sh
- echo -en 'travis_fold:end:script\\r'
